export const EXPECTATIONS_CONFIG = {
  financial: {
    title: "Financial Expectations",
    male_title: "Your Financial Obligations",
    female_title: "Financial Expectations",
    icon: "cash-outline" as const,
    description: "Set your financial expectations for marriage",
    male_description: "As the provider, set what you commit to financially for your family",
    female_description: "Set what you expect from your husband financially",
    fields: {
      primary_provider: {
        label: "Who should be the primary provider?",
        male_label: "How do you plan to fulfil your role as provider?",
        female_label: "What do you expect from your husband as a provider?",
        options: [
          { value: "husband", label: "Husband" },
          { value: "shared", label: "Shared equally" },
          { value: "flexible", label: "Flexible" },
        ],
      },
      expected_income_range: {
        label: "What income range do you expect?",
        male_label: "What income range do you aim to provide?",
        female_label: "What household income range do you expect?",
        options: [
          { value: "low", label: "Modest" },
          { value: "medium", label: "Comfortable" },
          { value: "high", label: "High earning" },
          { value: "flexible", label: "Flexible" },
        ],
      },
      financial_transparency: {
        label: "Should finances be fully transparent?",
        male_label: "Will you be fully transparent with your finances?",
        female_label: "Do you expect full financial transparency?",
        type: "boolean" as const,
        options: [
          { value: "true", label: "Yes, full transparency" },
          { value: "false", label: "Some privacy is fine" },
        ],
      },
      savings_expectations: {
        label: "What are your savings expectations?",
        male_label: "What savings approach will you commit to?",
        female_label: "What savings approach do you expect from the household?",
        options: [
          { value: "high", label: "Aggressive saving" },
          { value: "medium", label: "Moderate saving" },
          { value: "low", label: "Minimal saving" },
          { value: "none", label: "No expectations" },
        ],
      },
      wife_working: {
        label: "Should the wife work?",
        male_label: "Are you comfortable with your wife working?",
        female_label: "Do you plan to work after marriage?",
        options: [
          { value: "yes", label: "Yes" },
          { value: "part_time", label: "Part-time" },
          { value: "no", label: "No" },
          { value: "flexible", label: "Flexible" },
        ],
      },
    },
  },
  lifestyle: {
    title: "Lifestyle Expectations",
    male_title: "The Life You'll Build",
    female_title: "Your Lifestyle Expectations",
    icon: "home-outline" as const,
    description: "Define your lifestyle preferences",
    male_description: "Define the home and lifestyle you plan to build for your family",
    female_description: "Define the lifestyle and home environment you expect in your marriage",
    fields: {
      living_arrangement: {
        label: "Preferred living arrangement?",
        male_label: "Where do you plan to live after marriage?",
        female_label: "Where do you expect to live after marriage?",
        options: [
          { value: "separate", label: "Own place" },
          { value: "with_family", label: "With family" },
          { value: "flexible", label: "Flexible" },
        ],
      },
      work_life_balance: {
        label: "Approach to work-life balance?",
        male_label: "What household role dynamic will you uphold?",
        female_label: "What household role dynamic do you prefer?",
        options: [
          { value: "traditional", label: "Traditional roles" },
          { value: "modern", label: "Both contribute equally" },
          { value: "flexible", label: "Flexible" },
        ],
      },
      social_activities: {
        label: "Social activity level?",
        male_label: "What social lifestyle will you maintain as a family?",
        female_label: "What social lifestyle do you expect as a couple?",
        options: [
          { value: "conservative", label: "Private / minimal" },
          { value: "moderate", label: "Moderate" },
          { value: "active", label: "Very social" },
        ],
      },
      technology_usage: {
        label: "Technology & social media usage?",
        male_label: "What are your boundaries on personal social media at home?",
        female_label: "What do you expect around social media use in marriage?",
        options: [
          { value: "limited", label: "Limited" },
          { value: "moderate", label: "Moderate" },
          { value: "active", label: "Active" },
        ],
      },
      travel_expectations: {
        label: "Travel expectations?",
        male_label: "How much do you plan to travel with your family?",
        female_label: "How much do you expect to travel as a couple/family?",
        options: [
          { value: "frequent", label: "Frequent travel" },
          { value: "occasional", label: "Occasional trips" },
          { value: "rare", label: "Rare travel" },
          { value: "none", label: "Prefer staying home" },
        ],
      },
    },
  },
  mahr: {
    title: "Mahr",
    male_title: "Your Mahr Offer",
    female_title: "Your Mahr Expectations",
    icon: "gift-outline" as const,
    description: "Set your mahr preferences",
    male_description: "What mahr are you committed to offering?",
    female_description: "What mahr do you expect to receive?",
    fields: {
      mahr_type: {
        label: "Preferred type of mahr?",
        male_label: "What type of mahr are you willing to give?",
        female_label: "What type of mahr do you expect?",
        options: [
          { value: "cash", label: "Cash / monetary" },
          { value: "property", label: "Property / asset" },
          { value: "education", label: "Education / skill" },
          { value: "symbolic", label: "Symbolic" },
          { value: "flexible", label: "Flexible" },
        ],
      },
      mahr_range: {
        label: "Expected mahr range?",
        male_label: "What mahr range can you offer?",
        female_label: "What mahr range do you expect?",
        options: [
          { value: "symbolic", label: "Symbolic" },
          { value: "modest", label: "Modest" },
          { value: "moderate", label: "Moderate" },
          { value: "substantial", label: "Substantial" },
          { value: "flexible", label: "Flexible" },
        ],
      },
      payment_timeline: {
        label: "Payment timeline?",
        male_label: "When are you prepared to pay the mahr?",
        female_label: "When do you expect to receive the mahr?",
        options: [
          { value: "immediate", label: "Immediate (at nikah)" },
          { value: "deferred", label: "Deferred" },
          { value: "flexible", label: "Flexible" },
        ],
      },
      flexibility: {
        label: "How flexible are you on mahr?",
        male_label: "How flexible are you on what you offer?",
        female_label: "How flexible are you on your mahr expectations?",
        options: [
          { value: "strict", label: "Firm expectations" },
          { value: "moderate", label: "Somewhat flexible" },
          { value: "very_flexible", label: "Very flexible" },
        ],
      },
    },
  },
  religious: {
    title: "Religious Life",
    male_title: "Your Religious Commitments",
    female_title: "Your Religious Expectations",
    icon: "moon-outline" as const,
    description: "Set your religious expectations for the marriage",
    male_description: "Set your commitments around faith and worship as a husband",
    female_description: "Set your expectations for religious life in your marriage",
    fields: {
      prayer_together: {
        label: "Praying together as a couple?",
        male_label: "Will you establish congregational prayer at home with your wife?",
        female_label: "Do you want to pray together with your husband?",
        options: [
          { value: "always", label: "Always" },
          { value: "often", label: "Often" },
          { value: "sometimes", label: "Sometimes" },
          { value: "prefer_not", label: "Prefer not" },
        ],
      },
      religious_education_children: {
        label: "Religious education for children?",
        male_label: "How important is Islamic education for your children?",
        female_label: "How important is Islamic education for your children?",
        options: [
          { value: "essential", label: "Essential" },
          { value: "important", label: "Important" },
          { value: "preferred", label: "Preferred but flexible" },
        ],
      },
      religious_activities: {
        label: "Involvement in religious activities?",
        male_label: "How active will you be in the Muslim community?",
        female_label: "How active do you want to be in the Muslim community?",
        options: [
          { value: "very_active", label: "Very active" },
          { value: "active", label: "Active" },
          { value: "moderate", label: "Moderate" },
          { value: "minimal", label: "Minimal" },
        ],
      },
      madhhab_compatibility: {
        label: "How important is madhhab compatibility?",
        male_label: "How important is it that your wife follows the same madhhab?",
        female_label: "How important is it that your husband follows the same madhhab?",
        options: [
          { value: "essential", label: "Essential" },
          { value: "important", label: "Important" },
          { value: "preferred", label: "Preferred" },
          { value: "flexible", label: "Flexible" },
        ],
      },
    },
  },
  dress_code: {
    title: "Hijab & Modesty",
    male_title: "Modesty Expectations",
    female_title: "Your Hijab Practice",
    icon: "shirt-outline" as const,
    description: "Set expectations around hijab and modest dress",
    male_description: "Share what you expect from your wife in terms of hijab and modest dress",
    female_description: "Share your hijab practice and what you are committed to",
    fields: {
      hijab_level: {
        label: "Expected hijab level?",
        male_label: "What level of hijab do you expect your wife to maintain?",
        female_label: "What level of hijab do you currently maintain?",
        options: [
          { value: "hijab", label: "Hijab (headscarf)" },
          { value: "abaya_hijab", label: "Abaya + hijab" },
          { value: "niqab", label: "Niqab (face veil)" },
          { value: "flexible", label: "Flexible / her choice" },
        ],
      },
      abaya_outside: {
        label: "Wearing abaya outside the home?",
        male_label: "Do you expect your wife to wear abaya outside?",
        female_label: "Do you wear abaya outside the home?",
        options: [
          { value: "always", label: "Always" },
          { value: "most_settings", label: "In most settings" },
          { value: "flexible", label: "Flexible" },
          { value: "not_required", label: "Not required" },
        ],
      },
      dress_code_flexibility: {
        label: "How flexible are you on dress code?",
        male_label: "How flexible are you on your wife's dress code?",
        female_label: "Are you open to adjusting your dress code after marriage?",
        options: [
          { value: "firm", label: "Firm expectations" },
          { value: "open_discussion", label: "Open to discussion" },
          { value: "her_choice", label: "Fully her choice" },
        ],
      },
      mixed_gatherings: {
        label: "Dress code at mixed-gender gatherings?",
        male_label: "What do you expect at mixed-gender gatherings?",
        female_label: "How do you dress at mixed-gender gatherings?",
        options: [
          { value: "niqab", label: "Full niqab" },
          { value: "abaya_hijab", label: "Abaya + hijab" },
          { value: "modest_hijab", label: "Modest dress + hijab" },
          { value: "flexible", label: "Flexible" },
        ],
      },
    },
  },
  husband_obligations: {
    title: "Husband's Obligations",
    icon: "shield-checkmark-outline" as const,
    description: "Commitments expected from the husband",
    male_title: "Your Obligations as a Husband",
    male_description: "Acknowledge the obligations you commit to fulfilling:",
    female_title: "What You Expect From Your Husband",
    female_description: "Select the obligations you expect him to uphold:",
    fields: {
      provision: { label: "Financial provision for the family" },
      protection: { label: "Protection and safety of the family" },
      emotional_support: { label: "Emotional support and care" },
      fair_treatment: { label: "Fair and equal treatment" },
      kindness: { label: "Kindness and good character" },
      consultation: { label: "Consultation in decisions (shura)" },
      financial_responsibility: { label: "Responsible financial management" },
      religious_leadership: { label: "Religious guidance and leadership" },
    },
  },
  wife_obligations: {
    title: "Wife's Obligations",
    icon: "heart-outline" as const,
    description: "Commitments expected from the wife",
    male_title: "What You Expect From Your Wife",
    male_description: "Select the obligations you expect her to uphold:",
    female_title: "Your Obligations as a Wife",
    female_description: "Acknowledge the obligations you commit to fulfilling:",
    fields: {
      cooperation: { label: "Cooperation in building the home" },
      respect: { label: "Mutual respect" },
      trust: { label: "Trust and loyalty" },
      emotional_stability: { label: "Emotional support and stability" },
      household_management: { label: "Household management" },
      support_husband: { label: "Supporting the husband" },
      privacy: { label: "Guarding family privacy" },
      religious_observance: { label: "Religious observance" },
    },
  },
} as const;

// Step order for the form
export const EXPECTATIONS_STEPS = [
  "financial",
  "lifestyle",
  "mahr",
  "family",
  "religious",
  "obligations",
  "notes",
] as const;

export type ExpectationsStep = (typeof EXPECTATIONS_STEPS)[number];
