-- Replace Module 4 (Family Dynamics) with Hijab, Abaya & Modesty
-- Remove Module 8 if it was previously inserted
UPDATE public.marriage_course_modules
SET
  title = 'Hijab, Abaya & Modesty',
  description = 'Dress code expectations, abaya, niqab, and modest dress in marriage',
  video_url = NULL,
  expectations_category = 'dress_code',
  article_content = E'## Hijab, Abaya & Modesty in Marriage\n\nModesty is a core value in Islam. Allah says: *"And tell the believing women to lower their gaze and guard their chastity, and not to reveal their adornments except what normally appears. Let them draw their veils over their chests"* (Quran 24:31).\n\n## Understanding the Spectrum of Hijab\n\nMuslims hold a range of practices regarding women''s dress:\n\n**Hijab (headscarf):** The minimum that the majority of scholars consider obligatory. Covers the hair, neck, and ears while the face remains visible.\n\n**Abaya:** A full-length outer garment worn over clothing. Widely practiced in Arab cultures and by many Muslim women globally — a sign of dignity and modesty.\n\n**Niqab (face veil):** Covering the face in addition to the body. Some scholars consider it obligatory (Hanbali position); others consider it a virtuous recommendation. It is the personal choice of the woman, ideally in consultation with her husband.\n\n**Burqa:** A full body covering including the face and eyes, common in South Asian and Afghan traditions.\n\n## Scholarly Diversity on Niqab\n\nThere is genuine scholarly disagreement:\n\n- **Hanbali:** Niqab is wajib (obligatory)\n- **Hanafi, Maliki, Shafi''i majority:** Hijab is obligatory; niqab is mustahabb (recommended) or mubah (permitted)\n\nNeither spouse should be condemned for following a valid scholarly opinion. Respect for scholarly diversity is part of Islamic wisdom.\n\n## Key Principles for Couples\n\n**No compulsion in personal practice.** A husband may not force his wife to adopt a level of covering she has not chosen. Scholars are unanimous that a wife''s hijab is between her and Allah — the husband may encourage but must never coerce.\n\n**Aligned expectations reduce conflict.** If a man expects niqab and his wife has not chosen it, or a wife wears niqab and her husband is uncomfortable — these mismatches must be discussed openly *before* nikah, not discovered after.\n\n**Respect goes both ways.** A wife who practices niqab deserves a husband who supports and honours that. A wife who wears hijab deserves not to be pressured beyond what she has chosen.\n\n## Practical Considerations\n\nDiscuss the following before marriage:\n\n- What is your current practice and what are your expectations?\n- Are you open to adjusting, or is this a firm personal commitment?\n- How will you handle disagreements about dress code with grace?\n- What is your position on niqab specifically — obligation, recommendation, or personal choice?\n\n## Key Takeaway\n\nDress code is a deeply personal matter rooted in faith and identity. Enter marriage with honesty and mutual respect — not assumptions or pressure. The goal is a couple who are aligned, not a wife who is controlled.',
  is_active = true
WHERE module_number = 4;

-- Remove Module 8 if it exists
DELETE FROM public.marriage_course_modules WHERE module_number = 8;
