-- Add expectations_category and article_content columns to marriage_course_modules
ALTER TABLE public.marriage_course_modules
ADD COLUMN IF NOT EXISTS expectations_category TEXT;

ALTER TABLE public.marriage_course_modules
ADD COLUMN IF NOT EXISTS article_content TEXT;

-- Insert 7 modules with article content
INSERT INTO public.marriage_course_modules (module_number, title, description, video_url, expectations_category, article_content, is_active)
VALUES
  (1, 'Financial Responsibilities in Marriage',
   'Provider roles, shared finances, savings, transparency',
   NULL, 'financial',
   E'## The Islamic Framework for Finances in Marriage\n\nIslam places great emphasis on financial responsibility within marriage. The Quran states: *"Men are the protectors and maintainers of women, because Allah has made one of them to excel the other, and because they spend from their means"* (Quran 4:34).\n\n### The Provider Role (Nafaqah)\n\nThe husband has a primary obligation to provide for the household — this includes housing, food, clothing, and medical care. This doesn''t mean the wife cannot work or contribute, but the baseline responsibility rests with the husband.\n\nHowever, many modern Muslim couples choose to share financial responsibilities. What matters most is that both parties agree on their arrangement **before** marriage.\n\n### Financial Transparency\n\nThe Prophet Muhammad (peace be upon him) said: *"The best of you is the one who is best to his family"* (Tirmidhi). Financial transparency builds trust. Consider discussing:\n\n- Will you have joint or separate bank accounts?\n- How will major purchases be decided?\n- What percentage of income goes to savings?\n- How will you handle debt?\n\n### Savings & Planning\n\nIslam encourages moderation — neither extravagance nor miserliness. Planning for the future (children''s education, Hajj, emergencies) is a form of responsible stewardship (amanah).\n\n### Key Takeaway\n\nHave honest conversations about money **before** the nikah. Mismatched financial expectations are one of the top causes of marital conflict.',
   true),

  (2, 'Building a Lifestyle Together',
   'Living arrangements, work-life balance, social boundaries',
   NULL, 'lifestyle',
   E'## Creating Your Shared Life\n\nMarriage in Islam is described as a garment for one another — *"They are a garment for you and you are a garment for them"* (Quran 2:187). Building a lifestyle together means finding harmony in your daily routines and long-term goals.\n\n### Living Arrangements\n\nOne of the first practical decisions is where you''ll live. Islamically, a wife has the right to her own living space. While living with in-laws can work beautifully for some couples, it should be a mutual decision, not an assumption.\n\nConsider:\n- Do you prefer your own place or living with family?\n- What type of neighborhood matters to you?\n- How close do you want to be to your families?\n\n### Work-Life Balance\n\nWhether both spouses work, one stays home, or you have a flexible arrangement — the key is mutual agreement and respect. Traditional roles work for some families; modern shared roles work for others. Neither is wrong when both partners are happy.\n\n### Social Boundaries\n\nDiscuss your comfort levels around:\n- Socializing with friends (same-gender and mixed gatherings)\n- Social media presence and privacy\n- How much personal time vs. couple time you need\n- Hosting guests and frequency of social events\n\n### Technology & Screen Time\n\nIn the digital age, it''s worth discussing screen time boundaries, social media usage, and how you''ll protect your marriage from the distractions of constant connectivity.\n\n### Key Takeaway\n\nA successful marriage requires both partners to be intentional about the life they''re building — don''t leave major lifestyle decisions to assumption.',
   true),

  (3, 'Understanding Mahr',
   'Types of mahr, ranges, payment timelines',
   NULL, 'mahr',
   E'## Mahr: A Right, Not a Price\n\nMahr (dowry from the groom to the bride) is a fundamental right given to the wife in Islam. Allah says: *"And give the women their mahr as a free gift"* (Quran 4:4).\n\n### What is Mahr?\n\nMahr is a mandatory gift from the husband to the wife at the time of marriage. It belongs entirely to her — she can spend it, save it, or invest it as she wishes. It is NOT a purchase price; it is a symbol of commitment and respect.\n\n### Types of Mahr\n\n**Mahr Mu''ajjal (Immediate):** Paid at or before the nikah ceremony.\n\n**Mahr Mu''wajjal (Deferred):** An agreed amount to be paid at a later date or upon certain conditions (like divorce).\n\nMahr can be monetary, property, an educational pursuit (like memorizing Quran), or even something symbolic — the Prophet (peace be upon him) approved a mahr of teaching Quran.\n\n### Setting a Fair Mahr\n\nThe Prophet (peace be upon him) said: *"The best mahr is that which is easiest"* (Abu Dawud). Islam discourages excessive mahr that burdens the groom. At the same time, the bride''s right to a meaningful mahr should be respected.\n\nConsider:\n- What is reasonable given the groom''s financial situation?\n- Is the mahr symbolic, modest, moderate, or substantial?\n- When will it be paid — immediately or deferred?\n\n### Negotiation Etiquette\n\nMahr discussions should be respectful and involve both families. It''s not a negotiation to "win" — it''s an agreement that both parties feel good about.\n\n### Key Takeaway\n\nMahr is the wife''s Islamic right. Discuss it openly, set it fairly, and honor the agreement.',
   true),

  (4, 'Family Dynamics & In-Laws',
   'Family involvement, in-laws, cultural vs Islamic balance',
   NULL, 'family',
   E'## Navigating Family Relationships in Marriage\n\nThe Prophet Muhammad (peace be upon him) said: *"The best of you are those who are best to their families"* (Ibn Majah). Marriage doesn''t just join two people — it connects two families.\n\n### Family Involvement\n\nEvery family has different levels of involvement in their children''s lives. Some families are very close-knit with frequent gatherings; others give more independence. Neither is inherently better, but **mismatched expectations** about family involvement can cause real friction.\n\nDiscuss:\n- How involved do you expect your families to be in your marriage?\n- How will major decisions be made — just between you two, or with family input?\n- How will you handle unsolicited family advice?\n\n### In-Law Relationships\n\nIslam emphasizes kindness to both sets of parents. The Quran says: *"And We have enjoined upon man goodness to parents"* (29:8). However, your spouse comes first after Allah and His Messenger.\n\nPractical questions:\n- How often will you visit each family?\n- If there''s a conflict between your spouse and your parent, how will you handle it?\n- What are the boundaries around in-law visits to your home?\n\n### Cultural vs. Islamic Priorities\n\nMany marital conflicts stem from cultural expectations being confused with Islamic obligations. For example, Islam does NOT require a wife to live with her in-laws, serve them, or give up her own career — even if culture says otherwise.\n\nWhen culture and Islam conflict, Islam takes priority. But cultural traditions that don''t contradict Islam can be beautiful and enriching.\n\n### Key Takeaway\n\nSet clear, kind boundaries with both families early. Your marriage is your primary family unit — protect it while honoring your parents.',
   true),

  (5, 'Religious Life as a Couple',
   'Prayer together, children''s education, religious activities',
   NULL, 'religious',
   E'## Growing in Faith Together\n\nAllah says: *"And among His signs is that He created for you mates from among yourselves, that you may dwell in tranquility with them, and He has put love and mercy between your hearts"* (Quran 30:21).\n\nMarriage in Islam is an act of worship. Your spiritual life as a couple can be one of the most rewarding aspects of your relationship.\n\n### Praying Together\n\nThe Prophet (peace be upon him) said: *"May Allah have mercy on a man who gets up at night and prays, and wakes up his wife"* (Abu Dawud). Praying together strengthens your bond with Allah and with each other.\n\nConsider:\n- Will you pray together regularly?\n- How will you encourage each other spiritually without being forceful?\n- Will you read Quran together?\n\n### Children''s Religious Education\n\nIf you plan to have children, discuss:\n- How important is Islamic schooling vs. public school with weekend Islamic school?\n- At what age will children begin fasting and praying?\n- What Islamic values are non-negotiable in your household?\n- Will your children memorize Quran? To what extent?\n\n### Madhhab (School of Thought)\n\nIf you follow different madhhabs (Hanafi, Shafi''i, Maliki, Hanbali), discuss how you''ll handle differences in practice — especially around prayer, fasting, and halal food standards.\n\n### Religious Activities\n\nHow involved do you want to be as a couple in the Muslim community?\n- Attending Friday prayers together?\n- Volunteering at the masjid?\n- Attending Islamic lectures and halaqas?\n- Participating in Ramadan community events?\n\n### Key Takeaway\n\nAlign on your spiritual goals early. A couple that grows in faith together builds a marriage on the strongest foundation.',
   true),

  (6, 'Rights & Obligations',
   'Understanding your commitments as a spouse',
   NULL, 'obligations',
   E'## Rights & Obligations in Islamic Marriage\n\nIslam clearly defines the rights and responsibilities of both husband and wife. The Prophet (peace be upon him) said in his farewell sermon: *"O people, your wives have rights over you, and you have rights over them."*\n\n### The Husband''s Obligations\n\nThe husband is responsible for:\n\n**Financial Provision (Nafaqah):** Housing, food, clothing, and medical care for his wife and children. This is obligatory regardless of the wife''s own wealth.\n\n**Protection & Safety:** Ensuring the physical and emotional safety of the family.\n\n**Good Treatment:** The Prophet (peace be upon him) said: *"The most complete of believers in faith are those with the best character, and the best of you are the best to their women"* (Tirmidhi).\n\n**Fair & Just Treatment:** Making decisions with consultation (shura), being fair, and never being oppressive.\n\n**Religious Guidance:** Leading the family in matters of deen while being gentle and patient.\n\n### The Wife''s Obligations\n\nThe wife is responsible for:\n\n**Cooperation in Building the Home:** Working together with her husband to create a peaceful, loving household.\n\n**Mutual Respect & Trust:** Maintaining loyalty, trust, and respect in the relationship.\n\n**Guarding Family Privacy:** The Prophet (peace be upon him) said: *"The best of women is she who, when you look at her, she pleases you; when you command her, she obeys you; and when you are absent, she guards herself and your property"* (Nasai).\n\n**Supporting the Household:** While there is scholarly discussion about household duties, cooperation and mutual support are the spirit of Islamic marriage.\n\n### Mutual Rights\n\nBoth spouses share rights to:\n- Kindness and good treatment\n- Intimacy and companionship\n- Privacy and respect\n- Consultation in decisions\n- Personal space and growth\n\n### Key Takeaway\n\nKnowing your rights AND your obligations creates a balanced marriage. Focus on fulfilling your duties before demanding your rights.',
   true),

  (7, 'Final Reflections & Notes',
   'Reflect on what you''ve learned and add any additional thoughts',
   NULL, 'notes',
   E'## Bringing It All Together\n\nCongratulations on reaching the final module! You''ve covered the essential foundations of Islamic marriage:\n\n1. **Financial Responsibilities** — Understanding nafaqah, transparency, and shared planning\n2. **Lifestyle** — Aligning on living arrangements, work-life balance, and social boundaries\n3. **Mahr** — Knowing your rights and setting fair expectations\n4. **Family & In-Laws** — Setting healthy boundaries while honoring parents\n5. **Religious Life** — Growing in faith together as a couple\n6. **Rights & Obligations** — Understanding what Islam expects from both spouses\n\n### The Power of Communication\n\nThe single most important skill in marriage is **communication**. The Prophet Muhammad (peace be upon him) was known for his gentleness, patience, and willingness to listen to his wives. He consulted them, respected their opinions, and treated them with dignity.\n\nBefore you enter marriage, commit to:\n- Speaking honestly but kindly\n- Listening to understand, not just to respond\n- Addressing problems early before they grow\n- Never going to sleep angry without attempting reconciliation\n\n### Du''a for Marriage\n\nThe Quran teaches us to pray: *"Our Lord, grant us from among our wives and offspring comfort to our eyes and make us an example for the righteous"* (Quran 25:74).\n\nMake this du''a regularly. Ask Allah to bless your marriage, guide you both, and make your union a source of peace and strength.\n\n### Your Additional Notes\n\nUse the space below to write down any additional expectations, deal-breakers, or important thoughts that weren''t covered in the previous modules. This is your space to be completely honest about what matters most to you in a marriage.',
   true)
ON CONFLICT (module_number) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  expectations_category = EXCLUDED.expectations_category,
  article_content = EXCLUDED.article_content,
  video_url = EXCLUDED.video_url,
  is_active = EXCLUDED.is_active;
